apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookly
  name: bookly
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: bookly
  template:
    metadata:
      labels:
        app: bookly
    spec:
      containers:
      - image: fenrir7734/bookly-backend:latest
        name: bookly-backend
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 400m
            memory: 2048Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookly
  name: bookly
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bookly
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bookly-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookly
  minReplicas: 1
  maxReplicas: 5 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 20 
      policies:
        - type: Percent
          value: 50
          periodSeconds: 20

