INSERT INTO `author` VALUES (1,'Isaac','Asimov','1920-01-02',NULL,'1992-04-06','Isaac Asimov was a Russian-born, American author, a professor of biochemistry, and a highly successful writer, best known for his works of science fiction and for his popular science books.',NULL),
    (2,'Frank','Herbert','1920-09-08',NULL,'1986-02-11','Frank Herbert was a critically acclaimed and commercially successful American science fiction author. He is best known for the novel Dune and its five sequels. The Dune saga, set in the distant future and taking place over millennia, dealt with themes such as human survival and evolution, ecology, and the intersection of religion, politics, and power, and is widely considered to be among the classics in the field of science fiction.',NULL),
    (3,'George','Orwell','1903-06-25',NULL,'1950-01-21','Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism.',NULL),
    (4,'Stephen','King','1947-10-21',NULL,NULL,'Stephen Edwin King is an American author of horror, supernatural fiction, suspense, crime, science-fiction, and fantasy novels. Described as the King of Horror, a play on his surname and a reference to his high standing in pop culture, his books have sold more than 350 million copies, and many have been adapted into films, television series, miniseries, and comic books. King has published 64 novels, including seven under the pen name Richard Bachman, and five non-fiction books. He has also written approximately 200 short stories, most of which have been published in book collections.',NULL),
    (5,'J.R.R.','Tolkien','1892-01-03',NULL,'1973-10-02','John Ronald Reuel Tolkien: writer, artist, scholar, linguist. Known to millions around the world as the author of The Lord of the Rings, Tolkien spent most of his life teaching at the University of Oxford where he was a distinguished academic in the fields of Old and Middle English and Old Norse. His creativity, confined to his spare time, found its outlet in fantasy works, stories for children, poetry, illustration and invented languages and alphabets.',NULL),
    (7,'Andrzej','Sapkowski','1948-06-21',NULL,NULL,'Andrzej Sapkowski, born June 21, 1948 in Łódź, is a Polish fantasy writer. Sapkowski studied economics, and before turning to writing, he had worked as a senior sales representative for a foreign trade company. His first short story, The Witcher (Wiedźmin), was published in Fantastyka, Polands leading fantasy literary magazine, in 1986 and was enormously successful both with readers and critics. Sapkowski has created a cycle of tales based on the world of The Witcher, comprising three collections of short stories and five novels. This cycle and his many other works have made him one of the best-known fantasy authors in Poland in the 1990s.',NULL),
    (10,'Karol','Hetman','2022-05-03','2022-05-10 14:10:57.550745',NULL,'','2022-05-10 14:10:57.550776');

INSERT INTO `genre` VALUES
    (6,'ANTYUTOPIA'),
    (5,'BIOGRAFIA'),
    (1,'FANTASY'),
    (3,'HORROR'),
    (4,'KRYMINAŁ'),
    (2,'SCIFI'),
    (7,'SPACE OPERA');

INSERT INTO `book` VALUES (94,'2022-05-07','9788380625815',240,'1950-09-01','I, Robot','2022-05-07',1,2,'They mustnt harm a human being, they must obey hitman orders, and they must protect their own existence...but only so long as that doesnt violate rules one and two. With these Three Laws of Robotics, humanity embarked on perhaps its greatest adventure: the invention of the first positronic man. It was a bold new era of evolution that would open up enormous possibilities—and unforeseen risks. For the scientists who invented the earliest robots werent content that their creations should remain programmed helpers, companions, and semisentient worker-machines. And soon the robots themselves; aware of their own intelligence, power, and humanity, arent either. As humans and robots struggle to survive together—and sometimes against each other—on earth and in space, the future of both hangs in the balance. Human men and women confront robots gone mad, telepathic robots, robot politicians, and vast robotic intelligences that may already secretly control the world. And both are asking the same questions: What is human? And is humanity obsolete?\n\nIn l, Robot Isaac Asimov changes forever our perception of robots, and human beings and updates the timeless myth of mans dream to play god. with all its rewards—and terrors.',NULL),
    (95,'2022-05-07','9788381882484',232,'1953-09-01','The Caves of Steel','2022-05-07',1,2,'A millennium into the future two advancements have altered the course of human history: the colonization of the galaxy and the creation of the positronic brain. Isaac Asimovs Robot novels chronicle the unlikely partnership between a New York City detective and a humanoid robot who must learn to work together. Like most people left behind on an over-populated Earth, New York City police detective Elijah Baley had little love for either the arrogant Spacers or their robotic companions. But when a prominent Spacer is murdered under mysterious circumstances, Baley is ordered to the Outer Worlds to help track down the killer. The relationship between Life and his Spacer superiors, who distrusted all Earthmen, was strained from the start. Then he learned that they had assigned him a partner: R. Daneel Olivaw. Worst of all was that the \"R\" stood for robot--and his positronic partner was made in the image and likeness of the murder victim!',NULL),
    (96,'2022-05-07','9788378182320',216,'1958-01-01','The Naked Sun','2022-05-07',1,2,'A millennium into the future, two advancements have altered the course of human history: the colonization of the Galaxy and the creation of the positronic brain. On the beautiful Outer World planet of Solaria, a handful of human colonists lead a hermit-like existence, their every need attended to by their faithful robot servants.\n\nTo this strange and provocative planet comes Detective Elijah Baley, sent from the streets of New York with his positronic partner, the robot R. Daneel Olivaw, to solve an incredible murder that has rocked Solaria to its foundations. The victim had been so reclusive that he appeared to his associates only through holographic projection.\n\nYet someone had gotten close enough to bludgeon him to death while robots looked on. Now Baley and Olivaw are faced with two clear impossibilities: Either the Solarian was killed by one of his robots--unthinkable under the laws of Robotics--or he was killed by the woman who loved him so much that she never came into his presence!',NULL),
    (97,'2022-05-07','8371209242313',349,'1988-05-01','Prelude to Foundation','2022-05-07',1,2,'It is the year 12,020 G.E. and Emperor Cleon I sits uneasily on the Imperial throne of Trantor. Here in the great multidomed capital of the Galactic Empire, forty billion people have created a civilization of unimaginable technological and cultural complexity. Yet Cleon knows there are those who would see him fall—those whom he would destroy if only he could read the future.\n\nHari Seldon has come to Trantor to deliver his paper on psychohistory, his remarkable theory of prediction. Little does the young Outworld mathematician know that he has already sealed his fate and the fate of humanity. For Hari possesses the prophetic power that makes him the most wanted man in the Empire. . .the man who holds the key to the future—an apocalyptic power to be known forever after as the Foundation.',NULL),
    (98,'2022-05-07','8371209258432',325,'1993-01-01','Forward the Foundation','2022-05-07',1,2,'Here, from a grand master of science fiction, is the long awaited final novel of the greatest series ever told. Completed just before his death, Forward The Foundation is the crowning achievement of a great writers life, a stirring testament to the creative genius of Isaac Asimov.\n\nAs Hari Seldon struggles to perfect his revolutionary theory of psychohistory and ensure a place for humanity among the stars, the great Galactic Empire totters on the brink of apocalyptic collapse. Caught in the maelstrom are Seldon and all he holds dear, pawns in the struggle for dominance. Whoever can control Seldon will control psychohistory—and with it the future of the Galaxy.\n\nAmong those seeking to turn psychohistory into the greatest weapon known to man are a populist political demagogue, the weak-willed Emperor Cleon I, and a ruthless militaristic general. In his last act of service to humankind, Hari Seldon must somehow save his lifes work from their grasp as he searches for his true heirs—a search the begins with his own granddaughter and the dream of a new Foundation.',NULL),
    (99,'2022-05-07','9788381883405',204,'1951-05-30','Foundation','2022-05-07',1,2,'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future -- to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save mankind, Seldon gathers the best minds in the Empire -- both scientists and scholars -- and brings them to a bleak planet at the edge of the Galaxy to serve as a beacon of hope for a future generations. He calls his sanctuary the Foundation.\n\nBut soon the fledgling Foundation finds itself at the mercy of corrupt warlords rising in the wake of the receding Empire. Mankinds last best hope is faced with an agonizing choice: submit to the barbarians and be overrun -- or fight them and be destroyed.',NULL),
    (100,'2022-05-07','9788381881647',253,'1993-01-01','Foundation and Empire','2022-05-07',1,2,'Foundation and Empire tells the incredible story of a new breed of man who create a new force for galactic government. Thus, the Foundation hurtles into conflict with the decadent, decrepit First Empire. In this struggle for power amid the chaos of the stars, man stands at the threshold of a new, enlightened life which could easily be put aside for the old forces of barbarism. The Foundation novels of Isaac Asimov constitute what is very likely the most famed epic in all of science-fiction',NULL),
    (101,'2022-05-07','9788328095298',224,'1949-05-08','1984','2022-05-07',3,6,'Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwells nightmarish vision of a totalitarian, bureaucratic world and one poor stiffs attempt to find individuality. The brilliance of the novel is Orwells prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.',NULL),
    (102,'2022-05-07','9788381881388',784,'1965-05-01','Dune','2022-05-07',2,2,'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...\n\nWhen House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream.',NULL),
    (103,'2022-05-07','9788373017252',272,'1976-05-21','Dune Messiah','2022-05-07',2,2,'Book Two in the Magnificent Dune Chronicles--the Bestselling Science Fiction Adventure of All Time\n\nDune Messiah continues the story of Paul Atreides, better known--and feared--as the man christened MuadDib. As Emperor of the Known Universe, he possesses more power than a single man was ever meant to wield. Worshipped as a religious icon by the fanatical Fremens, Paul faces the enmity of the political houses he displaced when he assumed the throne--and a conspiracy conducted within his own sphere of influence.\n\nAnd even as House Atreides begins to crumble around him from the machinations of his enemies, the true threat to Paul comes to his lover, Chani, and the unborn heir to his familys dynasty...',NULL),
    (104,'2022-05-07','9788381880947',576,'1976-05-21','Children of Dune','2022-05-07',2,2,'Book three in Frank Herberts magnificent Dune Chronicles--one of the most significant sagas in the history of literary science fiction.\n\nThe Children of Dune are twin siblings Leto and Ghanima Atreides, whose father, the Emperor Paul MuadDib, disappeared in the desert wastelands of Arrakis nine years ago. Like their father, the twins possess supernormal abilities--making them valuable to their manipulative aunt Alia, who rules the Empire in the name of House Atreides.\n\nFacing treason and rebellion on two fronts, Alias rule is not absolute. The displaced House Corrino is plotting to regain the throne while the fanatical Fremen are being provoked into open revolt by the enigmatic figure known only as The Preacher. Alia believes that by obtaining the secrets of the twins prophetic visions, she can maintain control over her dynasty.\n\nBut Leto and Ghanima have their own plans for their visions--and their destinies....',NULL),
    (105,'2022-05-07','9788376488097',520,'1966-01-28','The Shining','2022-05-07',4,3,'Jack Torrances new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, hell have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.',NULL),
    (106,'2022-05-07','9788381257022',1104,'1986-01-28','It ','2022-05-07',4,3,'Welcome to Derry, Maine ...\n\nIt’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real ...\n\nThey were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But none of them can withstand the force that has drawn them back to Derry to face the nightmare without an end, and the evil without a name.',NULL),
    (107,'2022-05-07','9788365781314',320,'1982-04-12','The Gunslinger','2022-05-07',4,1,'In the first book of this brilliant series, Stephen King introduces readers to one of his most enigmatic heroes, Roland of Gilead, The Last Gunslinger. He is a haunting figure, a loner on a spellbinding journey into good and evil. In his desolate world, which frighteningly mirrors our own, Roland pursues The Man in Black, encounters an alluring woman named Alice, and begins a friendship with the Kid from Earth called Jake. Both grippingly realistic and eerily dreamlike, The Gunslinger leaves readers eagerly awaiting the next chapter.',NULL),
    (108,'2022-05-07','9788381162647',304,'1937-07-21','The Hobbit, or There and Back Again','2022-05-07',5,1,'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.\nWritten for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001).',NULL),
    (109,'2022-05-07','9788379855841',448,'1987-05-01','The Drawing of the Three','2022-05-07',4,1,'While pursuing his quest for the Dark Tower through a world that is a nightmarishly distorted mirror image of our own, Roland, the last gunslinger, encounters three mysterious doorways on the beach. Each one enters into the life of a different person living in contemporary New York.\n\nHere he links forces with the defiant young Eddie Dean and the beautiful, brilliant, and brave Odetta Holmes, in a savage struggle against underworld evil and otherworldly enemies.\n\nOnce again, Stephen King has masterfully interwoven dark, evocative fantasy and icy realism.',NULL),
    (110,'2022-05-07','9788375780659',340,'1994-01-01','Blood of Elves','2022-05-07',7,1,'The New York Times bestselling series that inspired the international hit video game: The Witcher. For over a century, humans, dwarves, gnomes, and elves have lived together in relative peace. But times have changed, the uneasy peace is over, and now the races are fighting once again. The only good elf, it seems, is a dead elf.\n\nGeralt of Rivia, the cunning assassin known as The Witcher, has been waiting for the birth of a prophesied child. This child has the power to change the world - for good, or for evil.\n\nAs the threat of war hangs over the land and the child is hunted for her extraordinary powers, it will become Geralts responsibility to protect them all - and the Witcher never accepts defeat.\n\nThe Witcher returns in this sequel to The Last Wish, as the inhabitants of his world become embroiled in a state of total war.\n\n',NULL),
    (111,'2022-05-07','9788375780666',368,'1995-01-01','The Time of Contempt','2022-05-07',7,1,'The New York Times bestselling series that inspired the international hit video game: The Witcher.\n\nGeralt is a witcher: guardian of the innocent; protector of those in need; a defender, in dark times, against some of the most frightening creatures of myth and legend. His task, now, is to protect Ciri. A child of prophecy, she will have the power to change the world for good or for ill -- but only if she lives to use it.',NULL),
    (112,'2022-05-07','9788375780673',382,'1996-01-01','Baptism of Fire','2022-05-07',7,1,'The Wizards Guild has been shattered by a coup and, in the uproar, Geralt was seriously injured. The Witcher is supposed to be a guardian of the innocent, a protector of those in need, a defender against powerful and dangerous monsters that prey on men in dark times.\n\nBut now that dark times have fallen upon the world, Geralt is helpless until he has recovered from his injuries.\n\nWhile war rages across all of the lands, the future of magic is under threat and those sorcerers who survive are determined to protect it. Its an impossible situation in which to find one girl - Ciri, the heiress to the throne of Cintra, has vanished - until a rumor places her in the Niflgaard court, preparing to marry the Emperor.\n\nInjured or not, Geralt has a rescue mission on his hands.\n\nThe Witcher returns in this action-packed sequel to The Time of Contempt.',NULL),
    (113,'2022-05-07','9788375780680',488,'1997-01-01','The Tower of the Swallow','2022-05-07',7,1,'The world has fallen into war. Ciri, the child of prophecy, has vanished. Hunted by friends and foes alike, she has taken on the guise of a petty bandit and lives free for the first time in her life. But the net around her is closing. Geralt, the Witcher, has assembled a group of allies determined to rescue her. Both sides of the war have sent brutal mercenaries to hunt her down. Her crimes have made her famous.\n\nThere is only one place left to run. The tower of the swallow is waiting...',NULL),
    (114,'2022-05-07','9788375780697',589,'1998-01-01','Lady of the Lake','2022-05-07',7,1,'After walking through the portal in the Tower of Swallows while narrowly escaping death, Ciri finds herself in a completely different world... an Elven world. She is trapped with no way out. Time does not seem to exist and there are no obvious borders or portals to cross back into her home world.\n\nBut this is Ciri, the child of prophecy, and she will not be defeated. She knows she must escape to finally rejoin the Witcher, Geralt, and his companions - and also to try to conquer her worst nightmare. Leo Bonhart, the man who chased, wounded and tortured Ciri, is still on her trail. And the world is still at war.',NULL);

INSERT INTO `user` VALUES (15,'Jan','Kowalski','jan.kowalski@gmail.com','48561280544','2022-05-07 12:09:10.747605','$2a$10$2xAaMtUnncvJPPY8eEUT8O7I8fwfzmyG4VUvDpHRedOa/BArPuZ7e','ROLE_USER','kowalski123', 0, 1),
    (16,'Adam','Nowak','adam.nowak@gmail.com','48561287644','2022-05-07 12:09:10.851201','$2a$10$f/qf0iiC29g9HFHA12iMn.gLK.uFq/7lr4cc.iLlD3/YtipUYrqhy','ROLE_USER','nowak912', 0, 1),
    (17,'Andrzej','Kowal','admin@gmail.com','48521280544','2022-05-07 12:09:10.956301','$2a$10$8wELS9L3PJPSSzygdoK2p.A9oCiMaqvLCNi9QWZeceCXZR954n7lS','ROLE_ADMIN','administrator', 0, 1),
    (18,'Marcin','Glapa','mod@gmail.com','48561284354','2022-05-07 12:09:11.062168','$2a$10$giHLgKkeLFH9exH7kzx7e.STyMbxyNi.xtPxiVutlB3dDIM0qHiGK','ROLE_MODERATOR','moderator', 0, 1),
    (20,'Karol','Hetman','hitex1999@gmail.com','48724580900','2022-05-13 11:17:52.287509','$2a$10$NdfnZPxuLw9g0eABVrV5C.3zRIVge8qJA9/yIUXGkrNjQdUSSc32q','ROLE_USER','user123', 0, 1);

INSERT INTO `shelf` VALUES (94,15,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','2022-05-07 12:09:11.116519',4,'2022-05-07 12:09:11.116543'),
    (94,16,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2022-05-07 12:09:11.124854',2,'2022-05-07 12:09:11.124898'),
    (95,15,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','2022-05-07 12:09:11.133483',5,'2022-05-07 12:09:11.133508'),
    (96,15,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','2022-05-07 12:09:11.142938',4,'2022-05-07 12:09:11.142965'),
    (97,15,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','2022-05-07 12:09:11.152583',5,'2022-05-07 12:09:11.152609');