apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bookly
  name: bookly
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: bookly
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bookly
    spec:
      containers:
      - image: fenrir7734/bookly-backend:latest
        name: bookly-backend
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookly
  name: bookly
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bookly
  type: ClusterIP
status:
  loadBalancer: {}
